# Generated by Django 4.0.4 on 2022-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_bill_nit_alter_client_document'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['first_name', 'last_name'], name='social_clie_first_n_e0ddf7_idx'),
        ),
    ]
