# Generated by Django 4.0.4 on 2022-06-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_client_social_clie_first_n_e0ddf7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='nit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.IntegerField(),
        ),
    ]
