# Generated by Django 4.0.4 on 2022-06-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_bill_nit_alter_client_document'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='social_clie_first_n_e0ddf7_idx',
        ),
    ]
